### ISSUE TITLE
[BUG] Latest Main branch commit breaks AsyncStreams (CurrentValue, Passthrough etc)

### ISSUE THREAD

**Issue by Prince2k3** [AsyncCommunity/AsyncExtensions#8] opened 2022-03-01 05:20 UTC
**Describe the bug**
I noticed a code behavior change since adding the actor code. 
For example, I use Passthrough as a way to pass events to an onReceive method. That stopped as it supposed the moment I updated to the updated main. The best I can describe the behavior is that fires once and then stops working after that. 

**To Reproduce**

```Swift
var events = AsyncStreams.Passthrough<Event>()

// I used 
events.nonBlockingSend(.myEvent)
```
then

```Swift 

// I have a modifier that wraps this in SwiftUI (onReceive)
task {
 do {
         for try await event in viewModel.events {
               switch event {
                   ...
               }
         }
     } catch {}
}

```

**Expected behavior**
AsyncStreams works like the commit `e4aeb0f` and before.

**Environment:**
 - Main

** Additional Info **

I'm not sure how to really explain what is going on here. This is the best I can do.

**Comment by twittemb** [comment] 2022-03-01 13:01
Hi @Prince2k3 

I'm currently rollbacking from using Actors for the Passthrough/CurrentValue/Replay streams due to potential losing some values while not being yet registered as a client of these streams.

Anyway, it could be nice if you could provide une repo that I could take a look at and make sure the next version will restore the expected behaviour.

thanks.

**Comment by twittemb** [comment] 2022-03-01 17:50
@Prince2k3 

could you check with that branch please ? -> https://github.com/AsyncCommunity/AsyncExtensions/tree/feature/multicast

for the record `nonBlockingSend` has been remove. you can use `send` directly.

**Comment by twittemb** [comment] 2022-03-01 19:48
There was an issue using an Actor to handle the registrations of new continuations in the streams (Passthrough, CurrentValue, Replay). The registration had to be Async since performed on an Actor. Unfortunately the creation of an AsyncStream offers a callback that does not supports Async. So the registrations had to be performed in a Task. In some occasions, some values could be pushed to the streams while the task was not yet executed. It resulted on loosing these values.

**Comment by Prince2k3** [comment] 2022-03-01 23:18
I reviewed the PR on the branch and used that branch to run through the usage in my current code. Seems to be working. I'll definitely be running more tests today.

@twittemb

**Comment by twittemb** [comment] 2022-03-03 18:06
@Prince2k3 hey

did you had the chance to perform further tests ? should we close the issue ?

thanks.

**Closed** 2022-03-03 18:32 UTC
Labels: bug

**Comment by twittemb** [comment] 2022-03-03 18:43
Thanks
